# Generated by Django 5.0.6 on 2024-06-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_post_delete_crawleddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachment',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
