# Generated by Django 5.0.6 on 2024-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_post_image_url_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
    ]
