# Generated by Django 5.0.6 on 2024-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterModelTable(
            name='post',
            table='search_post',
        ),
    ]
